### ISSUE TITLE
Header values cannot contain commas

### ISSUE THREAD

**Issue by mattj65817** [castorm/kafka-connect-http#101]
It would appear to be impossible to use `http.request.headers` to build a header which contains a comma in its value, since `TemplateHttpRequestFactory` uses `ConfigUtils.breakDownHeaders()` to parse comma-separated headers without any provision for allowing commas to be escaped. It ultimately uses `String.split(",")` to do this.

This presents a problem, for example, if one wants to include an `If-Modified-Since` header in the request. The recommended date format for this header (see [RFC2613, 3.3.1 Full Date](https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html)) somewhat stupidly includes a comma between the abbreviated day-of-week name and date/time parts. It's kind of silly that the day-of-week is in there, but it is.

`If-Modified-Since` is a *very* convenient header to include in order to minimize network traffic. It would be nice if it were supported in its "preferred" form.

It seems that the only change necessary would be to change the `itemSplitter` regex in `ConfigUtils.breakDownHeaders()` to only split on commas that *do not* follow some escape character. I am not familiar enough with the code base and typical usage patterns, however, to know whether this would present risk elsewhere.

**Comment by mattj65817** [comment]
...I somewhat underestimated the amount of work necessary. You'd have to change the `itemSplitter` regex and you'd *also* have to add a post-split phase to pull the escape characters out of the header values that contained them. Probably not a huge deal, but increases risk somewhat.

**Comment by castorm** [comment]
Hi Matt,

Thank you for reporting this.

It's not easy picking the right separator, so this was kind of bound to happen... The escape character sounds like a good option to keep backwards compatibility, I guess it just introduces some additional complexity.

Happy to accept a PR if you already have a proposal, otherwise I'll give it a try whenever I get a few minutes.

Best regards.

**Comment by mattj65817** [comment]
@castorm Sure, I'll take a shot at it and hopefully send a PR later in the day.
