### ISSUE TITLE
Maven package build fails on JDK 11.0.11

### ISSUE THREAD

**Issue by dingobar** [castorm/kafka-connect-http#133]
**Describe the bug**
It's the same bug as https://github.com/castorm/kafka-connect-http/issues/22, only a newer version.

See that issue for further details.

**Additional context**
JDK version 11.0.11 (current Ubuntu 20.04LTS default)

Quickfix:
Changing ${java.version} to 11 resolves the issue. Perhaps it would be possible to just take the major version of java instead of the entire version with bugfix?

**Comment by castorm** [comment]
Hi @dingobar,

Thank you very much for reporting this.

I believe this should be fixed by now via #134

It seems java.version wasn't defined as a maven property anywhere.

I hope that's enough.

Thanks,
Best regards.

**Comment by dingobar** [comment]
Confirmed! Thank you for the quick response, I'll close the issue 👍
