### ISSUE TITLE
Confluent Hub Update

### ISSUE THREAD

**Issue by joewood** [castorm/kafka-connect-http#27]
**Describe the bug**
I notice that the version published on Confluent Hub is 0.6.1 and not the latest version

Could you publish the latest version of the plugin, using Confluence Hub to install connectors enables a simpler workflow for Docker Image generation.

Great connector BTW.

**Comment by castorm** [comment]
Hi @joewood, thank you for your kind words.

Sure, I'll submit the latest version to Confluent Hub, and I'll try and be more prompt to submit future versions, at least any new minors & majors.

Sorry for any inconvenience.
Thanks,
Best regards.

**Comment by castorm** [comment]
Version [v0.7.6](https://github.com/castorm/kafka-connect-http/releases/tag/v0.7.6) has been submitted for approval, awaiting response.

**Comment by castorm** [comment]
Hey @joewood,

Latest version has been finally published on ConfluentHub:
https://www.confluent.io/hub/castorm/kafka-connect-http

Thanks,
Best regards.

**Comment by joewood** [comment]
Thanks @castorm, appreciate the speedy response.
