### ISSUE TITLE
Later release than 0.3.5 does not contains a connector

### ISSUE THREAD

**Issue by GDegrove** [castorm/kafka-connect-http#28]
Hello, 

First of all thanks for the connector and the work on it, I noticed while testing it. That the latest releases (after 0.3.5) of the connector does not contains the jar but only the source code.

According to the README, this is where the latest version should be retrieved. Did you change the site where you upload the connector? 
If yes where can we find it? If not, what is it needed to automate the release so it contains the jar?

**Comment by castorm** [comment]
Hi @GDegrove, thanks for your kind words.

I'm afraid, there were some changes in the deploy configuration around that version, and as a result, the connector package is not attached to the releases. I'll fix that or remove it from documentation.

In the meantime, connector package is available on maven central:
Latest version as of today can be found here (either the `zip` or the `tar.gz` would work for you):
https://repo1.maven.org/maven2/com/github/castorm/kafka-connect-http/0.7.6/

Connector is also present in Confluent Hub, although as described in https://github.com/castorm/kafka-connect-http/issues/27, it has been a little outdated.

Thanks for reporting this.
Best regards.

**Comment by GDegrove** [comment]
Thanks @castorm, appreciate the swift reply on this. 

I will have a look, if you need help do not hesitate, I can take some time to help you to resolve it, maintaining a project all by yourself is never easy and if I can ease the work, it'll be my pleasure.

**Comment by castorm** [comment]
Well, contributions are more than welcome.

This one in particular is related with the change from the travis build to github actions, I don't know what exactly would you need to give it a try, in terms of access and what not, as I understand just submitting a PR wouldn't be enough in this case.

Thanks,
Best regards.

**Comment by castorm** [comment]
Closing this as it has been finally resolved. All future releases will have the artifacts attached.
