### ISSUE TITLE
Why confluentControlCenterIntegration=false?

### ISSUE THREAD

**Issue by joewood** [castorm/kafka-connect-http#29]
**Is your feature request related to a problem? Please describe.**
I was wondering why you've set the Confluent Control Center Integration to false? The current released version seems to work OK. Was there a specific feature or licensing issue?

https://github.com/castorm/kafka-connect-http/blob/master/pom.xml#L319

**Comment by castorm** [comment]
Hi @joewood, not really.

I have never used Confluent Control Center, so when I read in the documentation of that property:
> Whether the component supports integration with Confluent Control Center.

I don't really know what that entails, so I cannot really assess whether the connector complies with the requirements of such integration or not.

I'm happy to turn that on if that's of any help.

Thanks,
Best regards.

**Comment by castorm** [comment]
Closing as there seems to be no action to be taken here.
