### ISSUE TITLE
Does the connector support HTTPS connection

### ISSUE THREAD

**Issue by GDegrove** [castorm/kafka-connect-http#30]
Hey @castorm, 

I was looking in the docs and I see entry regarding HTTPS support. I was wondering does the connector support TLS/SSL request? 
If you never tested, I can do it on my side and update the documenation accordingly.

The reason of the question, we want to poll ES with your connector and we are wondering if this would be feasible with TLS/SSL support without updating the HTTP client. 

Regards,
Gil

**Comment by castorm** [comment]
Hi @GDegrove,

I did actually test it in the past against the JIRA API, and I had no issues.

Please, give it a try and let me know if something doesn't work for you.

Thanks,
Best regards.

**Comment by castorm** [comment]
Closing as there seems to be no action to be taken here.
