### ISSUE TITLE
Is it possible to deal with pagination?

### ISSUE THREAD

**Issue by roniepaolo** [castorm/kafka-connect-http#45]
Hello,
I started to extract data from different APIs and I ran into an endpoint that use pagination in this way:

JSON response:
```
{
  "success":true,
  "data":[
    {},
    {},
    ...
  ],
  "additional_data":{
    "pagination":{
      "start":0,
      "limit":100,
      "more_items_in_collection":true,
      "next_start":100
    }
  }
}
```

The endpoint allows to set the 'start' and the 'limit' in the GET request, but I can't set these elements as the offset in the connector conf because my list pointer is 'data'. Is there a way to deal with pagination like this? If not, I'll be grateful if there are some suggestions to implement this feature.

Thanks.

**Comment by castorm** [comment]
Hi @roniepaolo,

I'm afraid that's not possible as of today, and it's kind of intentionally like that to prevent the issues of deep pagination and to encourage capturing changes (which would be really hard with those arbitrary properties start/limit).

However, just to make sure we can't solve this any other way:
- Does the data you are after contain any sort of unique identifier?
- Does the data you are after contain any sort of create/update dates?
- Does the API allow you to query filtering inequality (>=) by any of the above?
- Does the API allow you to sort results by any of the above?

Best regards.

**Comment by castorm** [comment]
Thanks for your feedback @roniepaolo,

I'm trying to picture how this would look like for your specific scenario. The fact that you can sort by id/update time but not filter by them leaves one of two options:

**Sorting by update time descending**
- You would fetch the page 0
- You would fetch the following pages (1..N) until you reach a record already seen (N contains already seen record)
- You would start over

**Sorting by update time ascending**
- You would fetch the page N+1 (N being the last requested page)
- You would fetch the following pages (N+1..M) until there are no more records (M)
- You would start over

I believe the second option aligns better with this connector, I can only think of two issues:
- Every request you make will be at the end of the paginated resultset, potentially exercising some underlying deep pagination, not good in terms of resource usage and performance. We can live with this as long as users know what they are doing, and this is a last resort.
- All records in a page will share the same page number, and last page might be incomplete. This makes the logic for advancing the offset a bit more complex. In the event of failure, and provided we are after at-least-once delivery, even though the last processed record was in page N, we cannot request page N+1, we would need to request page N again, at least until the last record in a full page is processed.

Does this make sense? Did you have anything else in mind?

Thanks,
Best regards.
-
