### ISSUE TITLE
How to map the individual JSON fields to topic fields?

### ISSUE THREAD

**Issue by ryandanielspmc** [castorm/kafka-connect-http#57]
I may be missing something in the documentation, and if so, my apologies, but when I get the data, and put it into the topic, has all of the JSON in a `VALUE` field. I would like to map the individual JSON fields to their own topic message fields. Is that possible with this connector?

**Comment by castorm** [comment]
Hi @ryandanielspmc,

It is possible, however, that entails either knowing before-hand or inferring the schema from your JSON document and what's more challenging, that would require dealing with schema changes. Offering a general-purpose solution for that is not straightforward, and that's the reason it's currently not implemented as part of the connector.

But as I said, it's possible to implement your own and still benefit from the rest of the features of this connector by implementing [KvSourceRecordMapper](https://github.com/castorm/kafka-connect-http/blob/master/src/main/java/com/github/castorm/kafka/connect/http/record/spi/KvSourceRecordMapper.java)
```
@FunctionalInterface
public interface KvSourceRecordMapper extends Configurable {

    SourceRecord map(KvRecord record, Partition partition);

    default void configure(Map<String, ?> map) {
        // Do nothing
    }
}
```

You'd just pack your own implementation with the connector and define its usage through the configuration property `http.response.record.mapper`.

I hope this helps.

Best regards.

**Comment by ryandanielspmc** [comment]
I will give that a shot. Thank you.

**Comment by ryandanielspmc** [comment]
I see that the example interface above is from `0.8.0-SNAPSHOT`. Is that going to be released soon?

**Comment by castorm** [comment]
Hi @ryandanielspmc 

That example is common for both the last released version and 0.8.0-SNAPSHOT.

In any case, the latter has been reverted due to an issue we found, so the last release v0.7.6 is pretty much same as master.

Best regards.

**Comment by atomotic** [comment]
maybe this Connect SMT is the answer for this problem: https://github.com/RedHatInsights/expandjsonsmt

seen today from this tweet: https://twitter.com/gunnarmorling/status/1346761627543154688

**Comment by castorm** [comment]
Thanks @atomotic for sharing this, I just added a reference in the README.md file.
