### ISSUE TITLE
Importing project on both eclipse and intellij gives error

### ISSUE THREAD

**Issue by vishnu-chalil** [castorm/kafka-connect-http#71]
I tried importing the project on both intellij and eclipse but lots of errors just pops up. No other projects gives these errors. What could be the reason. I have attached a snap below

![BugPNG](https://user-images.githubusercontent.com/23023241/100472467-4dce6680-3102-11eb-9975-bdbfad1ec8a1.PNG)

**Comment by castorm** [comment]
Hi @vishnu-chalil,

I'm afraid that's [lombok](https://projectlombok.org/).

It requires a plugin both for [eclipse](https://projectlombok.org/setup/eclipse) and [intellij](https://projectlombok.org/setup/intellij)

I hope that helps.

Best regards.

**Comment by vishnu-chalil** [comment]
That did help. Thanks :)
