### ISSUE TITLE
Debugging in Intellij

### ISSUE THREAD

**Issue by vishnu-chalil** [castorm/kafka-connect-http#74]
A quick question . How do I debug this in Intellij without exporting as jar everytime to libs folder of  Kafka.  Iam using apache kafka. I want to check the code flow in Intellij. Is there anyway to do this.

**Comment by castorm** [comment]
Hi @vishnu-chalil,

99% of cases it's enough simulating what Kafka Connect does. For that I'd recommend you take a look at the following test:
https://github.com/castorm/kafka-connect-http/blob/master/kafka-connect-http-test/src/test/java/com/github/castorm/kafka/connect/http/HttpSourceConnectorIT.java

That test runs a WireMock server with some mocked responses, you can skip that part if you want to hit the real API.

What I want you to focus on is the next bit, where it reads all records from your connector, simulating the connector lifecycle:
```java
Map<String, String> config = getConfigMap(replaceVariables(readConnectorConfig("connectors/connector1.json"), properties));

List<SourceRecord> records = readAllRecords(config);
```

All those are static methods available here:
https://github.com/castorm/kafka-connect-http/blob/master/kafka-connect-http-test/src/test/java/com/github/castorm/kafka/connect/ConnectorUtils.java

I hope this helps.

Best regards.

**Comment by vishnu-chalil** [comment]
Yeah sure it helps but I wanted to know if there is a debugging mode or similar mechanism to check the code flow like checking the code flow in spring boot application.

**Comment by castorm** [comment]
That's what I was trying to say, once you do as I said, you can then debug your test, adding any breakpoints you might like.

**Comment by vishnu-chalil** [comment]
I understood it but didn't understand how to debug the flow the files inside the records package etc. from what point in execution are those files acessed, what are their functionalities etc. Do correct me if Iam asking the same question. But I couldnt yet understand how to debug through those.

**Comment by vishnu-chalil** [comment]
Thanks Castrom. What you said is making sense once I started working on it. Saved my day :)
