### ISSUE TITLE
Authorization header

### ISSUE THREAD

**Issue by atomotic** [castorm/kafka-connect-http#83]
When setting an Authorization header:
```
http.request.headers=Authorization=Bearer xxxxxxxx
```

i got this error:
```
java.lang.IllegalStateException: Incomplete pair: Authorization=Bearer xxxxxxxx
```

I tried also enclosing the value in `"` or `'`. 
The http service i'm scraping allows to pass the authorization token also as http argument, and it's working this way.
Thanks!

**Comment by castorm** [comment]
Hi @atomotic,

I'm afraid it's not due to quotes, but the header name-value pair separator, which in this case should be `:` instead of `=`.

Please, let me know if there is something we can improve int the docs or the examples.

I hope this helps.

Best regards.

**Comment by atomotic** [comment]
ah, got it! yes, `:` works.
maybe i can send you the example i'm working with, is for capturing changes from an https://airtable.com spreadsheet.
thanks.
