### ISSUE TITLE
Setting up the http.request.body field

### ISSUE THREAD

**Issue by igrishaev** [castorm/kafka-connect-http#94]
Hello! 

First, thank you for the library, that's really great to have a free version of HTTP connector (compared to the one from Confluent which is paid). My first question is, how can I put the message's payload into the body of the request. I'm expecting to have something like:

```
"http.request.body": "${message.payload}"
```

or similar (assuming that the messages from a topic are in JSON). But this doesn't work.

The more general question is, how can I know all the possible fields that I reference in the template? I know you use Freemaker as a template engine, but what is the context for it?

Thank you,
Ivan

**Comment by igrishaev** [comment]
Sorry, it looks like misunderstood something. I thought that the library provides an HTTP Sink functionality so I could redirect JSON messages out from the topic to an HTTP endpoint. But judging by the #26 it's not possible at the moment, so my question is obsolete I guess.

**Comment by castorm** [comment]
Hello @igrishaev ,

You are right, this connector only implements an HTTP Source, not Sink.

Maybe at some point in the future it will, but for now I'm afraid it doesn't. :(

Best regards.
